version: "3.4"
services:
    php-fpm:
        image: php-fpm
        container_name: php-fpm
        restart: always
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        environment:
            TZ: America/Sao_Paulo
        depends_on:
            - database
        volumes:
            - ${APPLICATION}:/var/www/html
        networks:
            - now-network
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        volumes:
            - ${APPLICATION}:/var/www/html
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_API_PORT}:${NGINX_HOST_API_PORT}"
            - "${NGINX_HOST_WEB_PORT}:${NGINX_HOST_WEB_PORT}"
        depends_on:
            - php-fpm
        environment:
            TZ: America/Sao_Paulo
        networks:
            - now-network
    database:
        image: postgres:latest
        container_name: database
        restart: always
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
            - postgres_data:${POSTGRES_DATA_DIR}
        environment:
            TZ: America/Sao_Paulo
            PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        networks:
            - now-network
networks:
    now-network:
        driver: bridge
volumes:
    postgres_data:
        driver: local
